### ISSUE TITLE
Support for backward-compatibile string syntax u'str' in Python 3.3

### ISSUE THREAD

**Issue by xilexio** [bjpop/language-python#11]
From docs http://docs.python.org/3.3/reference/lexical_analysis.html#string-and-bytes-literals :
New in version 3.3: Support for the unicode legacy literal (u'value') was reintroduced to simplify the maintenance of dual Python 2.x and 3.x codebases.

In language-python 0.4.0, Language.Python.Version3:
`parseExpr "u'x'" "stdin"`
gives parse error - unexpected token. Version2 works fine.

**Comment by bjpop** [comment]
This has been fixed in 24fd2a271d69029d876dd03b2c9ffd49c15d22af
