### ISSUE TITLE
Confusing Dot operator

### ISSUE THREAD

**Issue by xilexio** [bjpop/language-python#12]
`Dot` being an `Op` data type operator is confusing, as its rhs is an expression (always `Var`), while it should be an `Ident` (see Python grammar). In a way, it's the only lhs/rhs of any operator expressions that should not be evaluated as-is, because it's not a real variable, but only a field name. Currently rhs `Var` has role of a hacky container for an `Ident` here.
I suggest removing `Dot` from `Op` data type and adding it as an `Expr`, for example
`Dot { dot_expr :: Expr annot, dot_field :: Ident annot, expr_annot :: annot }`

**Comment by bjpop** [comment]
Good idea @xilexio. Thanks for the suggestion. This is now implemented in ae8b81e8b4371a9400c5228ba404104576380c6b.
