### ISSUE TITLE
`Functor` instances

### ISSUE THREAD

**Issue by Gabriel439** [bjpop/language-python#16]
Is it possible to make `Module` (and everything underneath it) a `Functor`, so that I can use `fmap` to change what is stored in the `annot` fields?  For example, if I wanted to just delete the annotations, I could do:

```haskell
fmap (\_ -> ()) :: Module SrcSpan -> Module ()
```

Actually, I think you could go a step further and make `Module` an instance of `Comonad` (and then you would use `extract` instead of `annot`), but I'm perfectly happy with just a `Functor` instance.

**Comment by bjpop** [comment]
Done in aae2d0b18402a892512bb90553ae8f94c353e858, thanks to DeriveFunctor.

Needed to rejig the way Comprehensions are represented to allow the Functor instance to work.

**Comment by Gabriel439** [comment]
Awesome!  Thank you very much :)

**Comment by bjpop** [comment]
No worries. Sorry it took so long.
