### ISSUE TITLE
Relax utf8-string dependency

### ISSUE THREAD

**Issue by rul** [bjpop/language-python#24]
Hi,

Is there a reason why your library depends exactly on utf8-string version 1? Will it really not work with "utf8-string == 1.0.0.1"?  Maybe you could relax it a bit, so as it's easier for you to support future versions of the package.

**Comment by bjpop** [comment]
Hi @rul I've relaxed the dependency to:

utf8-string >= 1 && < 2

It might work with more versions but I haven't had time to check.

If you think it should be more liberal please let me know.

**Comment by FranklinChen** [comment]
Can you upload this new version to Hackage?

**Comment by bjpop** [comment]
That should be up on Hackage now.

https://hackage.haskell.org/package/language-python

Version 0.5.2

Please check and let me know if there are any issues.
