### ISSUE TITLE
pretty printer forces very long lines

### ISSUE THREAD

**Issue by sebfisch** [bjpop/language-python#3]
The [`Pretty`](http://hackage.haskell.org/packages/archive/language-python/0.3.2/doc/html/Language-Python-Common-Pretty.html#t:Pretty) instances for the AST allow few newlines, especially in expressions. Why not use [`sep`](http://haskell.org/ghc/docs/7.0.3/html/libraries/pretty-1.0.1.2/Text-PrettyPrint-HughesPJ.html#v:sep) instead of [`hsep`](http://haskell.org/ghc/docs/7.0.3/html/libraries/pretty-1.0.1.2/Text-PrettyPrint-HughesPJ.html#v:hsep) in the definition of [`commaList`](http://hackage.haskell.org/packages/archive/language-python/0.3.2/doc/html/src/Language-Python-Common-Pretty.html#commaList)?

(edited to include links for identifiers)

**Comment by ppelleti** [comment]
The place where I'm running into this problem is with keyword arguments, such as:

```
kicad_mod.append(Text(type="reference", text="REF**", at=[0.0, 12.5], rotation=0.0, layer="F.SilkS", size=[1.0, 1.0], thickness=0.15, hide=False))
```
