### ISSUE TITLE
Nested assignments misparsed

### ISSUE THREAD

**Issue by jkoppel** [bjpop/language-python#32]
"x = y = 1" gets incorrectly parsed to "x, y = 1", which gives an error when executed.

The fundamental problem is that assignments are treated as statements in the AST, even though they are not statements in the grammar.

**Comment by bjpop** [comment]
Thanks for the bug report. It was a problem with the pretty printer. Has been fixed in 7f6d3b2bb667394e73fb2d3be87cdd5f375ece18, thanks to a pull request from @mkovacs. Bumped version to 0.5.5.
