### ISSUE TITLE
Please make a release with recent bug fixes

### ISSUE THREAD

**Issue by LucianU** [bjpop/language-python#42]
I tried to install `language-python` from Hackage and it didn't compile with GHC 8.4, because of issues fixed here 0a7b671e7deea6ec731433d1d1ed967daf122535. It would be great if you could make this fix available on Hackage.

**Comment by tych0** [comment]
I've hit this as well now too, a release would be great.

**Comment by tych0** [comment]
Ping, any chance we can get a release?

**Comment by bjpop** [comment]
Sorry for the delay. I'm trying to make a release now. Ran into a hurdle with my hackage account. Once that is resolved, a new release will be made ASAP.

**Comment by bjpop** [comment]
I've now made a release on Hackage. Latest version number is 0.5.6.

You can find it here:

http://hackage.haskell.org/package/language-python-0.5.6

Very sorry for the delays.

**Comment by tych0** [comment]
No problem, thanks for releasing!
