### ISSUE TITLE
Add language-python to Stackage?

### ISSUE THREAD

**Issue by ersran9** [bjpop/language-python#62]
Would you consider adding language-python to Stackage? You can find instructions [here](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by bjpop** [comment]
I've made a pull request:

https://github.com/commercialhaskell/stackage/pull/5509

**Comment by bjpop** [comment]
The pull request has been merged. I assume I can close this ticket now?

**Comment by ersran9** [comment]
Thanks!
